# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'LoginUi.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_LoginWindow(object):
    def setupUi(self, LoginWindow):
        LoginWindow.setObjectName("LoginWindow")
        LoginWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(LoginWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 70, 321, 471))
        self.frame.setStyleSheet("#frame {  \n"
"    \n"
"    \n"
"    background-image: url(:/icons/icon/b_r.png);\n"
" \n"
"    border-top-left-radius: 20px;  \n"
";\n"
"    border-bottom-left-radius: 20px;  \n"
"  \n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 50, 281, 51))
        self.label.setStyleSheet("font: 28pt \"幼圆\";\n"
"font: 20pt \"French Script MT\";\n"
"font: 18pt \"Agency FB\";")
        self.label.setObjectName("label")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(340, 70, 341, 471))
        self.frame_2.setStyleSheet("#frame_2 {\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1, stop:0 rgba(250, 209, 208, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:1,\n"
"    stop:0 rgba(255, 165, 165, 255), stop:1 rgba(255, 255, 255, 255));\n"
"    border-top-right-radius: 20px;\n"
"    border-bottom-right-radius: 20px;\n"
"}")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setGeometry(QtCore.QRect(-10, 49, 351, 401))
        self.frame_3.setMinimumSize(QtCore.QSize(351, 401))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.frame_5 = QtWidgets.QFrame(self.frame_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_5.sizePolicy().hasHeightForWidth())
        self.frame_5.setSizePolicy(sizePolicy)
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_4 = QtWidgets.QFrame(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(6)
        sizePolicy.setHeightForWidth(self.frame_6.sizePolicy().hasHeightForWidth())
        self.frame_6.setSizePolicy(sizePolicy)
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.stackedWidget_2 = QtWidgets.QStackedWidget(self.frame_6)
        self.stackedWidget_2.setStyleSheet("QLineEdit{\n"
"background-color:rgba(255,255,255,0);\n"
"border: none; /* 无边框 */  \n"
"    border-bottom: 1px solid black;\n"
"}\n"
"QPushButton{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}")
        self.stackedWidget_2.setObjectName("stackedWidget_2")
        self.page_register = QtWidgets.QWidget()
        self.page_register.setObjectName("page_register")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.page_register)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.lineEdit_R_account = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_account.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_R_account.setObjectName("lineEdit_R_account")
        self.verticalLayout_6.addWidget(self.lineEdit_R_account)
        self.lineEdit_Email = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_Email.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_Email.setObjectName("lineEdit_Email")
        self.verticalLayout_6.addWidget(self.lineEdit_Email)
        self.lineEdit_R_password_1 = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_password_1.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_R_password_1.setObjectName("lineEdit_R_password_1")
        self.verticalLayout_6.addWidget(self.lineEdit_R_password_1)
        self.lineEdit_R_password_2 = QtWidgets.QLineEdit(self.page_register)
        self.lineEdit_R_password_2.setMinimumSize(QtCore.QSize(0, 25))
        self.lineEdit_R_password_2.setObjectName("lineEdit_R_password_2")
        self.verticalLayout_6.addWidget(self.lineEdit_R_password_2)
        self.pushButton_R_sure = QtWidgets.QPushButton(self.page_register)
        self.pushButton_R_sure.setMinimumSize(QtCore.QSize(0, 35))
        self.pushButton_R_sure.setObjectName("pushButton_R_sure")
        self.verticalLayout_6.addWidget(self.pushButton_R_sure)
        self.stackedWidget_2.addWidget(self.page_register)
        self.page_Login = QtWidgets.QWidget()
        self.page_Login.setObjectName("page_Login")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.page_Login)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.lineEdit_L_account = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_L_account.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_L_account.setObjectName("lineEdit_L_account")
        self.verticalLayout_5.addWidget(self.lineEdit_L_account)
        self.lineEdit_L_password = QtWidgets.QLineEdit(self.page_Login)
        self.lineEdit_L_password.setMinimumSize(QtCore.QSize(0, 40))
        self.lineEdit_L_password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.lineEdit_L_password.setObjectName("lineEdit_L_password")
        self.verticalLayout_5.addWidget(self.lineEdit_L_password)
        self.pushButton_L_sure = QtWidgets.QPushButton(self.page_Login)
        self.pushButton_L_sure.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_L_sure.setObjectName("pushButton_L_sure")
        self.verticalLayout_5.addWidget(self.pushButton_L_sure)
        self.stackedWidget_2.addWidget(self.page_Login)
        self.verticalLayout_4.addWidget(self.stackedWidget_2)
        self.verticalLayout_3.addWidget(self.frame_6)
        self.frame_7 = QtWidgets.QFrame(self.frame_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.frame_7.sizePolicy().hasHeightForWidth())
        self.frame_7.setSizePolicy(sizePolicy)
        self.frame_7.setStyleSheet("QPushButton{\n"
"boreder:none;\n"
"}\n"
"QPushButton:pressed{\n"
"padding-top:5px;\n"
"padding-left:5px;\n"
"}")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_7)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton_Login = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Login.setStyleSheet("image: url(:/icons/icon/登录.png);")
        self.pushButton_Login.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../icon/登录.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Login.setIcon(icon)
        self.pushButton_Login.setObjectName("pushButton_Login")
        self.horizontalLayout.addWidget(self.pushButton_Login)
        self.pushButton_Register = QtWidgets.QPushButton(self.frame_7)
        self.pushButton_Register.setStyleSheet("image: url(:/icons/icon/注册.png);")
        self.pushButton_Register.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("../icon/注册.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_Register.setIcon(icon1)
        self.pushButton_Register.setObjectName("pushButton_Register")
        self.horizontalLayout.addWidget(self.pushButton_Register)
        self.verticalLayout_3.addWidget(self.frame_7)
        self.verticalLayout_2.addWidget(self.frame_4)
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.page)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.page_2)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_2 = QtWidgets.QLabel(self.page_2)
        self.label_2.setStyleSheet("color: rgb(255, 40, 12);\n"
"font: 10pt \"隶书\";")
        self.label_2.setObjectName("label_2")
        self.verticalLayout_9.addWidget(self.label_2)
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.page_3)
        self.horizontalLayout_2.setContentsMargins(15, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_4 = QtWidgets.QLabel(self.page_3)
        self.label_4.setStyleSheet("color: rgb(255, 42, 14);\n"
"font: 11pt \"隶书\";")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_2.addWidget(self.label_4)
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.page_4)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_3 = QtWidgets.QLabel(self.page_4)
        self.label_3.setStyleSheet("color: rgb(255, 29, 8);\n"
"font: 10pt \"隶书\";")
        self.label_3.setObjectName("label_3")
        self.verticalLayout_7.addWidget(self.label_3)
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setObjectName("page_5")
        self.label_5 = QtWidgets.QLabel(self.page_5)
        self.label_5.setGeometry(QtCore.QRect(130, 20, 101, 31))
        self.label_5.setStyleSheet("color: rgb(255, 0, 0);\n"
"font: 10pt \"隶书\";")
        self.label_5.setObjectName("label_5")
        self.stackedWidget.addWidget(self.page_5)
        self.verticalLayout_2.addWidget(self.stackedWidget)
        self.verticalLayout.addWidget(self.frame_5)
        self.pushButton = QtWidgets.QPushButton(self.frame_2)
        self.pushButton.setGeometry(QtCore.QRect(280, 0, 71, 41))
        self.pushButton.setStyleSheet("QPushButton{  \n"
"    border: none;  \n"
"}")
        self.pushButton.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icon/closeCircle.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton.setIcon(icon2)
        self.pushButton.setIconSize(QtCore.QSize(35, 35))
        self.pushButton.setObjectName("pushButton")
        LoginWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(LoginWindow)
        self.statusbar.setObjectName("statusbar")
        LoginWindow.setStatusBar(self.statusbar)

        self.retranslateUi(LoginWindow)
        self.stackedWidget_2.setCurrentIndex(1)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(LoginWindow)

    def retranslateUi(self, LoginWindow):
        _translate = QtCore.QCoreApplication.translate
        LoginWindow.setWindowTitle(_translate("LoginWindow", "MainWindow"))
        self.label.setText(_translate("LoginWindow", "机器学习实验平台"))
        self.lineEdit_R_account.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.lineEdit_Email.setPlaceholderText(_translate("LoginWindow", "邮箱："))
        self.lineEdit_R_password_1.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.lineEdit_R_password_2.setPlaceholderText(_translate("LoginWindow", "确认密码："))
        self.pushButton_R_sure.setText(_translate("LoginWindow", "注册"))
        self.lineEdit_L_account.setPlaceholderText(_translate("LoginWindow", "账号："))
        self.lineEdit_L_password.setPlaceholderText(_translate("LoginWindow", "密码："))
        self.pushButton_L_sure.setText(_translate("LoginWindow", "确认登陆"))
        self.label_2.setText(_translate("LoginWindow", "       密码不能为空！！！"))
        self.label_4.setText(_translate("LoginWindow", "     密码或账号错误！！！"))
        self.label_3.setText(_translate("LoginWindow", "        密码不一致！！！"))
        self.label_5.setText(_translate("LoginWindow", "注册成功！"))
import res_rc
